module.exports = {
  purge: [],
  theme: {
    extend: {
      backgroundColor: {
        'orange-peel': '#eae0c8',
        'blue-royal':'#04305D',
        'blue-royal-light':'#0754A0',
        'silver':'#D3D3D3',
        'gold':'#FFD700',
        'drakula-background':'#282a36	',
        'drakula-current':'#44475a	',
        'drakula-foreground':'#f8f8f2',
        'drakula-comment':'#6272a4',
        'drakula-cyan':'#8be9fd',
        'drakula-green':'#50fa7b',
        'drakula-orange':'#ffb86c',
        'drakula-pink':'#ff79c6',
        'drakula-purple':'#bd93f9',
        'drakula-red':'#ff5555',
        'drakula-yellow':'#f1fa8c',
      },
      textColor: {
        'orange-peel': '#eae0c8',
        'blue-royal':'#04305D',
        'blue-royal-light':'#0754A0',
        'silver':'#D3D3D3',
        'gold':'#FFD700',
        'drakula-background':'#282a36	',
        'drakula-current':'#44475a	',
        'drakula-foreground':'#F8F8F2	',
        'drakula-comment':'#6272a4',
        'drakula-cyan':'#8be9fd',
        'drakula-green':'#50fa7b',
        'drakula-orange':'#ffb86c',
        'drakula-pink':'#ff79c6',
        'drakula-purple':'#bd93f9',
        'drakula-red':'#ff5555',
        'drakula-yellow':'#f1fa8c',

      },
      borderColor: {
        'orange-peel': '#eae0c8',
        'blue-royal':'#04305D',
        'blue-royal-light':'#0754A0',
        'silver':'#D3D3D3',
        'gold':'#FFD700',
        'drakula-background':'#282a36	',
        'drakula-current':'#44475a	',
        'drakula-foreground':'#f8f8f2',
        'drakula-comment':'#6272a4',
        'drakula-cyan':'#8be9fd',
        'drakula-green':'#50fa7b',
        'drakula-orange':'#ffb86c',
        'drakula-pink':'#ff79c6',
        'drakula-purple':'#bd93f9',
        'drakula-red':'#ff5555',
        'drakula-yellow':'#f1fa8c',

      },
    },
  },
  variants: {},

  plugins: [],
};
